from time import time

tic = time()

dict_url = {}

old_url = {
"Обзор портативных раций Icom ": "/dokumentacija/obzor-portativnykh-ratsiy-icom-/",
"Обзор радиостанции Vertex VZ-30": "/dokumentacija/obzor-radiostantsii-vertex-vz-30/",
"Обзор новых портативных раций КОМБАТ T-34": "/dokumentacija/obzor-novykh-portativnykh-ratsiy-kombat-t-34/",
"AVAYA – коммуникационные решения нового уровня": "/dokumentacija/avaya-kommunikatsionnye-resheniya-novogo-urovnya/",
"Обзор телефонов Panasonic ": "/dokumentacija/obzor-telefonov-panasonic-/",
"Обзор раций Kenwood": "/dokumentacija/obzor-ratsiy-kenwood/",
"Рации TurboSky - новинка отечественного рынка": "/dokumentacija/ratsii-turbosky-novinka-otechestvennogo-rynka/",
"Обзор автомобильных радиостанций ICOM": "/dokumentacija/obzor-avtomobilnykh-radiostantsiy-icom/",
"Обзор автомобильных радиостанций Vertex Standard": "/dokumentacija/obzor-avtomobilnykh-radiostantsiy-vertex-standard/",
"Применение IP-АТС для организации эффективной связи внутри компании": "/dokumentacija/primenenie-ip-ats-dlya-organizatsii-effektivnoy-svyazi-vnutri-kompanii/",
"Промышленные телефоны ТАШ - надежная связь в любых условиях": "/dokumentacija/promyshlennye-telefony-tash-nadezhnaya-svyaz-v-lyubykh-usloviyakh/",
"Обзор факсов Panasonic и факс-серверов Yeastar: виды особенности как выбрать и купить факс": "/dokumentacija/obzor-faksov-panasonic-i-faks-serverov-yeastar-vidy-osobennosti-kak-vybrat-i-kupit-faks/",
"Обзор раций Hytera": "/dokumentacija/obzor-ratsiy-hytera/",
"Обзор радиостанций MotoTRBO": "/dokumentacija/obzor-radiostantsiy-mototrbo/",
"Стандарт TETRA": "/dokumentacija/standart-tetra/",
"Обзор любительских КВ трансиверов": "/dokumentacija/obzor-lyubitelskikh-kv-transiverov/",
"Разбираем стандарт DMR на примере радиостанций Hytera": "/dokumentacija/razbiraem-standart-dmr-na-primere-radiostantsiy-hytera/",
"Радиостанции Icom как образец качества японского производства": "/dokumentacija/radiostantsii-icom-kak-obrazets-kachestva-yaponskogo-proizvodstva/",
"Выбираем подходящий ip-телефон среди представителей Panasonic и Yealink": "/dokumentacija/vybiraem-podkhodyashchiy-ip-telefon-sredi-predstaviteley-panasonic-i-yealink/",
"Обзор IP-АТС Panasonic KX-NCP1000RU  и KX-NCP500RU ": "/dokumentacija/obzor-ip-ats-panasonic-kx-ncp1000ru-i-kx-ncp500ru-/",
"Как сэкономить на офисной связи используя VoIP-шлюз": "/dokumentacija/kak-sekonomit-na-ofisnoy-svyazi-ispolzuya-voip-shlyuz/",
"Обзор SIP DECT телефона Panasonic KX-TGP600 ": "/dokumentacija/obzor-sip-dect-telefona-panasonic-kx-tgp600-/",
"Panasonic KX-NSX: надежная и гибкая UC-платформа": "/dokumentacija/panasonic-kx-nsx-nadezhnaya-i-gibkaya-uc-platforma/",
"Будущее стандарта DMR и аналого-цифровой миграции": "/dokumentacija/budushchee-standarta-dmr-i-analogo-tsifrovoy-migratsii/",
"Дешевая связь при помощи DECT раций и мобильных телефонов": "/dokumentacija/deshevaya-svyaz-pri-pomoshchi-dect-ratsiy-i-mobilnykh-telefonov/",
"Мобильный коммуникатор Wave от Motorola Solutions": "/dokumentacija/mobilnyy-kommunikator-wave-ot-motorola-solutions/",
"Преимущества IP-телефонии для торговых сетей": "/dokumentacija/preimushchestva-ip-telefonii-dlya-torgovykh-setey/",
"Преимущества традиционных раций для транспортных компаний ASEAN и не только": "/dokumentacija/preimushchestva-traditsionnykh-ratsiy-dlya-transportnykh-kompaniy-asean-i-ne-tolko/",
"Строительные рации для связи в условиях стройки": "/dokumentacija/stroitelnye-ratsii-dlya-svyazi-v-usloviyakh-stroyki/",
"Современные возможности коммуникаций и виды связи": "/dokumentacija/sovremennye-vozmozhnosti-kommunikatsiy-i-vidy-svyazi/",
"SIP-телефония SIP-протокол ключевые возможности": "/dokumentacija/sip-telefoniya-sip-protokol-klyuchevye-vozmozhnosti/",
"Незаметная связь: портативные радиостанции и скрытые гарнитуры": "/dokumentacija/nezametnaya-svyaz-portativnye-radiostantsii-i-skrytye-garnitury/",
"Молодым дорогу: обзор новых портативных раций на сайте": "/dokumentacija/molodym-dorogu-obzor-novykh-portativnykh-ratsiy-na-sayte/",
"Кто на новенького: обзор IP-телефонов и IP-АТС": "/dokumentacija/kto-na-novenkogo-obzor-ip-telefonov-i-ip-ats/",
"Решения на базе оборудования Motorola для розничных сетей": "/dokumentacija/resheniya-na-baze-oborudovaniya-motorola-dlya-roznichnykh-setey/",
"Что такое радиостанция (рация)?": "/dokumentacija/chto-takoe-radiostantsiya-ratsiya-/",
"Что такое трансивер?": "/dokumentacija/chto-takoe-transiver/",
"Что такое ресивер?": "/dokumentacija/chto-takoe-resiver/",
"Что такое приемник радиоприемник?": "/dokumentacija/chto-takoe-priemnik-radiopriemnik/",
"Обзор IP-АТС Yeastar S-серии": "/dokumentacija/obzor-ip-ats-yeastar-s-serii/",
"Что такое Интернет-телефония?": "/dokumentacija/chto-takoe-internet-telefoniya/",
"Что такое стационарная радиостанция?": "/dokumentacija/chto-takoe-statsionarnaya-radiostantsiya/",
"Что такое факс?": "/dokumentacija/chto-takoe-faks/",
"Что такое виртуальная АТС?": "/dokumentacija/chto-takoe-virtualnaya-ats/",
"Что такое сетевой коммутатор?": "/dokumentacija/chto-takoe-setevoy-kommutator/",
"Как выбрать рацию для туризма?": "/dokumentacija/kak-vybrat-ratsiyu-dlya-turizma/",
"Безлицензионные частоты в РФ - нужно ли регистрировать радиостанцию?": "/dokumentacija/bezlitsenzionnye-chastoty-v-rf-nuzhno-li-registrirovat-radiostantsiyu/",
"Взрывозащищенное оборудование связи": "/dokumentacija/vzryvozashchishchennoe-oborudovanie-svyazi/",
"NXDN – новый протокол цифровой радиосвязи": "/dokumentacija/nxdn-novyy-protokol-tsifrovoy-radiosvyazi/",
"Новое решение в стандарте TETRA от Motorola": "/dokumentacija/novoe-reshenie-v-standarte-tetra-ot-motorola/",
"Линейка Motorola MOTOTRBO": "/dokumentacija/lineyka-motorola-mototrbo/",
"Mototrbo Capacity Max - система полного транкинга от Motorola": "/dokumentacija/mototrbo-capacity-max-sistema-polnogo-trankinga-ot-motorola/",
"Специализированные устройства и ПО Motorola Solutions для служб реагирования": "/dokumentacija/spetsializirovannye-ustroystva-i-po-motorola-solutions-dlya-sluzhb-reagirovaniya/",
"Почему выгодно купить радиостанцию Терек?": "/dokumentacija/pochemu-vygodno-kupit-radiostantsiyu-terek/",
"Обзор новой портативной радиостанции Motorola ST7500 ": "/dokumentacija/obzor-novoy-portativnoy-radiostantsii-motorola-st7500-/",
"Обзор новых радиостанций Icom": "/dokumentacija/obzor-novykh-radiostantsiy-icom/",
"Краткий обзор преимуществ сетевого оборудования MikroTik ": "/dokumentacija/kratkiy-obzor-preimushchestv-setevogo-oborudovaniya-mikrotik-/",
"Обзор бренда и новинок Snom": "/dokumentacija/obzor-brenda-i-novinok-snom/",
"Рации Motorola соответствуют требованиям ПП №969": "/dokumentacija/ratsii-motorola-sootvetstvuyut-trebovaniyam-pp-969/",
"Обзор новой портативной радиостанции Motorola MTP6650": "/dokumentacija/obzor-novoy-portativnoy-radiostantsii-motorola-mtp6650/",
"Лучшее время купить рацию АРГУТ": "/dokumentacija/luchshee-vremya-kupit-ratsiyu-argut/",
"Чем хороша IP-телефония": "/dokumentacija/chem-khorosha-ip-telefoniya/",
"IP-телефония LG-Ericsson iPECS": "/dokumentacija/ip-telefoniya-lg-ericsson-ipecs/",
"Автомобильная радиостанция Optim-778": "/dokumentacija/avtomobilnaya-radiostantsiya-optim-778/",
"Grandstream: IP-телефония для бизнеса": "/dokumentacija/grandstream-ip-telefoniya-dlya-biznesa/",
"Кenwood: обзор портативных и автомобильных раций": "/dokumentacija/kenwood-obzor-portativnykh-i-avtomobilnykh-ratsiy/",
"Hytera — качественная радиосвязь для профессионалов": "/dokumentacija/hytera-kachestvennaya-radiosvyaz-dlya-professionalov/",
"Snom D385 - немецкий IP телефон для крутого офиса": "/dokumentacija/snom-d385-nemetskiy-ip-telefon-dlya-krutogo-ofisa/",
"Как убедить руководителя перейти на VoIP?": "/dokumentacija/kak-ubedit-rukovoditelya-pereyti-na-voip/",
"Snom DECT облегчает работу в любых организациях": "/dokumentacija/snom-dect-oblegchaet-rabotu-v-lyubykh-organizatsiyakh/",
"VoiP Yeastar для улучшения качества обслуживания клиентов": "/dokumentacija/voip-yeastar-dlya-uluchsheniya-kachestva-obsluzhivaniya-klientov/",
"Как IP телефония расширяет границы офиса": "/dokumentacija/kak-ip-telefoniya-rasshiryaet-granitsy-ofisa/",
"Hytera предлагает рации и модули для работы на стройке": "/dokumentacija/hytera-predlagaet-ratsii-i-moduli-dlya-raboty-na-stroyke/",
"VoIP телефония снижает затраты на бизнес": "/dokumentacija/voip-telefoniya-snizhaet-zatraty-na-biznes/",
"Hytera: радиосвязь на рынке туристических услуг": "/dokumentacija/hytera-radiosvyaz-na-rynke-turisticheskikh-uslug/",
"Как выбрать между облачной или локальной IP АТС": "/dokumentacija/kak-vybrat-mezhdu-oblachnoy-ili-lokalnoy-ip-ats/",
"Icom: обзор новых портативных радиостанций": "/dokumentacija/icom-obzor-novykh-portativnykh-radiostantsiy/",
"Что такое односайтовые и многосайтовые системы связи?": "/dokumentacija/chto-takoe-odnosaytovye-i-mnogosaytovye-sistemy-svyazi/",
"Что такое стандарт DMR и чем он хорош?": "/dokumentacija/chto-takoe-standart-dmr-i-chem-on-khorosh/",
"Аргут: портативные рации для работы и отдыха": "/dokumentacija/argut-portativnye-ratsii-dlya-raboty-i-otdykha/",
"Motorola представляет рации для профессионалов и любителей": "/dokumentacija/motorola-predstavlyaet-ratsii-dlya-professionalov-i-lyubiteley/",
"DMR радиосвязь и аналоговые радиостанции": "/dokumentacija/dmr-radiosvyaz-i-analogovye-radiostantsii/",
"Бесплатная связь за границей и на отдыхе": "/dokumentacija/besplatnaya-svyaz-za-granitsey-i-na-otdykhe/",
"SIP-телефоны: возможности рынка IP-телефонии в 2020 году": "/dokumentacija/sip-telefony-vozmozhnosti-rynka-ip-telefonii-v-2020-godu/",
"Как выбрать рацию для работы и отдыха": "/dokumentacija/17322/",
"НОВЫЙ ЭТАП БОЛЬШОГО ПУТИ": "/dokumentacija/novyy-etap-bolshogo-puti/",
"ПЕРЕХОД НА «ЦИФРУ» - ПРАВИЛЬНО": "/dokumentacija/perekhod-na-tsifru-pravilno/",
"Что такое IP-телефония?": "/dokumentacija/chto-takoe-ip-telefoniya/",
"Обзор IP-телефона Escene ES292": "/dokumentacija/obzor-ip-telefona-escene-es292/",
"Скачать и установить рингтон для IP-телефонов Yealink": "/dokumentacija/skachat-i-ustanovit-rington-dlya-ip-telefonov-yealink/",
"Таблица совместимости для гарнитур Mairdi": "/dokumentacija/tablitsa-sovmestimosti-dlya-garnitur-mairdi/",
"Профессиональные системы радиосвязи для служб охраны и мобильных групп ": "/dokumentacija/professionalnye-sistemy-radiosvyazi-dlya-sluzhb-okhrany-i-mobilnykh-grupp-/",
"Универсальная транкинговая радиосвязь от Hytera": "/dokumentacija/universalnaya-trankingovaya-radiosvyaz-ot-hytera/",
"IP-камеры как средство организации видеонаблюдения": "/dokumentacija/ip-kamery-kak-sredstvo-organizatsii-videonablyudeniya/",
"Обзор IP-АТС от Yeastar": "/dokumentacija/obzor-ip-ats-ot-yeastar/",
"Grandstream расширяет линейку IP-видеотелефонов": "/dokumentacija/grandstream-rasshiryaet-lineyku-ip-videotelefonov/",
"5 новых возможностей офисных IP-телефонов": "/dokumentacija/5-novykh-vozmozhnostey-ofisnykh-ip-telefonov/",
"Подготовка к настройке АТС": "/dokumentacija/podgotovka-k-nastroyke-ats/",
"Обеспечение телефонной связью удаленных подвижных объектов ": "/dokumentacija/obespechenie-telefonnoy-svyazyu-udalennykh-podvizhnykh-obektov-/",
"50 лет производителю ICOM": "/dokumentacija/50-let-proizvoditelyu-icom/",
"Второе поколение NEXEDGE": "/dokumentacija/vtoroe-pokolenie-nexedge/",
"Как выбрать IP-телефон": "/dokumentacija/kak-vybrat-ip-telefon/",
"IP-телефоны Panasonic и Escene: сравнение": "/dokumentacija/ip-telefony-panasonic-i-escene-sravnenie/",
"VoIP-шлюзы Yeastar NeoGate: TA400 TA410 и TA810": "/dokumentacija/voip-shlyuzy-yeastar-neogate-ta400-ta410-i-ta810/",
"Расшифровка аббревиатур ATEX на радиостанциях": "/dokumentacija/rasshifrovka-abbreviatur-atex-na-radiostantsiyakh/",
"SIP телефоны Yealink: обзор линеек T3 и T4": "/dokumentacija/sip-telefony-yealink-obzor-lineek-t3-i-t4/",
"Обзор портативных радиостанций Kenwood": "/dokumentacija/obzor-portativnykh-radiostantsiy-kenwood/",
"IP телефоны Grandstream для малого бизнеса: обзор": "/dokumentacija/ip-telefony-grandstream-dlya-malogo-biznesa-obzor/",
"Цифровые радиостанции eVerge™ от Vertex Standard": "/dokumentacija/tsifrovye-radiostantsii-everge-ot-vertex-standard/",
"Рынок SIP-телефонов в России": "/dokumentacija/rynok-sip-telefonov-v-rossii/",
"Как выбрать портативные рации для охоты и рыбалки": "/dokumentacija/kak-vybrat-portativnye-ratsii-dlya-okhoty-i-rybalki/",
"Цифровая радиосвязь с берега на катер": "/dokumentacija/tsifrovaya-radiosvyaz-s-berega-na-kater/",
"SIP-телефоны Yealink T4: обзор серии": "/dokumentacija/sip-telefony-yealink-t4-obzor-serii/",
"SIP-телефоны Escene": "/dokumentacija/sip-telefony-escene/",
"Обзор SIP-телефона Fanvil X5": "/dokumentacija/obzor-sip-telefona-fanvil-x5/",
"Обзор IP-АТС Atcom": "/dokumentacija/obzor-ip-ats-atcom/",
"Архитектура SIP телефонии": "/dokumentacija/arkhitektura-sip-telefonii/",
"IP-телефония - что это и как работает": "/dokumentacija/ip-telefoniya-chto-eto-i-kak-rabotaet/",
"Как самостоятельно подключить IP-телефонию": "/dokumentacija/kak-samostoyatelno-podklyuchit-ip-telefoniyu/",
"Настройка OpenVPN-туннеля для IP-телефонов Yealink ": "/dokumentacija/nastroyka-openvpn-tunnelya-dlya-ip-telefonov-yealink-/",
"Как настроить IP-АТС?": "/dokumentacija/kak-nastroit-ip-ats/",
"Радиостанции Megajet: особенности и разнообразие": "/dokumentacija/radiostantsii-megajet-osobennosti-i-raznoobrazie/",
"Как выбрать автомобильную рацию": "/dokumentacija/kak-vybrat-avtomobilnuyu-ratsiyu/",
"Обзор автомобильной радиостанции MegaJet MJ-600 PLUS": "/dokumentacija/obzor-avtomobilnoy-radiostantsii-megajet-mj-600-plus/",
"Обзор автомобильных Си-Би раций Megajet": "/dokumentacija/obzor-avtomobilnykh-si-bi-ratsiy-megajet/",
"Обзор портативных радиостанций для охоты рыбалки и другого активного отдыха": "/dokumentacija/obzor-portativnykh-radiostantsiy-dlya-okhoty-rybalki-i-drugogo-aktivnogo-otdykha/",
"Рации VERTEX: сравнение характеристик": "/dokumentacija/ratsii-vertex-sravnenie-kharakteristik/",
"Развитие радиосвязи: виды радиостанций": "/dokumentacija/razvitie-radiosvyazi-vidy-radiostantsiy/",
"IP-телефоны – выбор связи для Вашего бизнеса": "/dokumentacija/ip-telefony-vybor-svyazi-dlya-vashego-biznesa/",
"Обзор портативных радиостанций Vector (Вектор)": "/dokumentacija/obzor-portativnykh-radiostantsiy-vector-vektor/",
"Как повысить прибыльность с IP-АТС?": "/dokumentacija/kak-povysit-pribylnost-s-ip-ats/",
"Обзор IP-телефона DECT Yealink SIP-W52P": "/dokumentacija/obzor-ip-telefona-dect-yealink-sip-w52p/",
"IP-телефония на примере SIP-телефона от Yealink": "/dokumentacija/ip-telefoniya-na-primere-sip-telefona-ot-yealink/",
"Megajet 350 vs Yosan Excalibur – обзор Си-Би радиостанций": "/dokumentacija/megajet-350-vs-yosan-excalibur-obzor-si-bi-radiostantsiy/",
"Диапазоны и типы портативных радиостанций": "/dokumentacija/diapazony-i-tipy-portativnykh-radiostantsiy/",
"Обзор портативных раций Vertex Standard": "/dokumentacija/obzor-portativnykh-ratsiy-vertex-standard/",
"Автомобильные Си-Би радиостанции": "/dokumentacija/avtomobilnye-si-bi-radiostantsii/",
"7 фактов о Yealink которые необходимо знать если вас интересует VoIP-телефония": "/dokumentacija/7-faktov-o-yealink-kotorye-neobkhodimo-znat-esli-vas-interesuet-voip-telefoniya/",
"5 достоинств профессиональных портативных радиостанций КОМБАТ": "/dokumentacija/5-dostoinstv-professionalnykh-portativnykh-radiostantsiy-kombat/",
"Решение по организации IP-телефонии для офиса на базе оборудования Yeastar и Yealink": "/dokumentacija/reshenie-po-organizatsii-ip-telefonii-dlya-ofisa-na-baze-oborudovaniya-yeastar-i-yealink/",
"Обзор взрывозащищенных радиостанций Hytera PD795Ex Motorola DP4401 Ex и Kenwood NX-230EXE": "/dokumentacija/obzor-vzryvozashchishchennykh-radiostantsiy-hytera-pd795ex-motorola-dp4401-ex-i-kenwood-nx-230exe/",
"Обзор VoIP телефонов Snom серии 7x": "/dokumentacija/obzor-voip-telefonov-snom-serii-7x/",
"Первый взгляд на DECT телефон Gigaset A54OH": "/dokumentacija/pervyy-vzglyad-na-dect-telefon-gigaset-a54oh/",
}

new_url = {
"Что такое односайтовые и многосайтовые системы связи?": "/blog/tematicheskie-stati/chto-takoe-odnosaytovye-i-mnogosaytovye-sistemy-svyazi/",
"VoIP телефония снижает затраты на бизнес": "/blog/tematicheskie-stati/voip-telefoniya-snizhaet-zatraty-na-biznes/",
"Тест Категория 2": "/blog/tematicheskie-stati/10_predmetov_bez_kotorykh_ne_oboytis_letom/",
"IP-телефония LG-Ericsson iPECS": "/blog/tematicheskie-stati/ip-telefoniya-lg-ericsson-ipecs/",
"DMR радиосвязь и аналоговые радиостанции": "/blog/tematicheskie-stati/dmr-radiosvyaz-i-analogovye-radiostantsii/",
"Преимущества IP-телефонии для торговых сетей": "/blog/tematicheskie-stati/preimushchestva-ip-telefonii-dlya-torgovykh-setey/",
"Чем хороша IP-телефония": "/blog/tematicheskie-stati/chem-khorosha-ip-telefoniya/",
"SIP-телефоны: возможности рынка IP-телефонии в 2020 году": "/blog/tematicheskie-stati/sip-telefony-vozmozhnosti-rynka-ip-telefonii-v-2020-godu/",
"Что такое стационарная радиостанция?": "/blog/tematicheskie-stati/chto-takoe-statsionarnaya-radiostantsiya/",
"Как выбрать между облачной или локальной IP АТС": "/blog/tematicheskie-stati/kak-vybrat-mezhdu-oblachnoy-ili-lokalnoy-ip-ats/",
"Что такое стандарт DMR и чем он хорош?": "/blog/tematicheskie-stati/chto-takoe-standart-dmr-i-chem-on-khorosh/",
"Новое решение в стандарте TETRA от Motorola": "/blog/tematicheskie-stati/novoe-reshenie-v-standarte-tetra-ot-motorola/",
"Что такое ресивер?": "/blog/tematicheskie-stati/chto-takoe-resiver/",
"Что такое приемник радиоприемник?": "/blog/tematicheskie-stati/chto-takoe-priemnik-radiopriemnik/",
"Что такое Интернет-телефония?": "/blog/tematicheskie-stati/chto-takoe-internet-telefoniya/",
"Что такое факс?": "/blog/tematicheskie-stati/chto-takoe-faks/",
"Что такое виртуальная АТС?": "/blog/tematicheskie-stati/chto-takoe-virtualnaya-ats/",
"Что такое сетевой коммутатор?": "/blog/tematicheskie-stati/chto-takoe-setevoy-kommutator/",
"Как выбрать рацию для туризма?": "/blog/tematicheskie-stati/kak-vybrat-ratsiyu-dlya-turizma/",
"Безлицензионные частоты в РФ - нужно ли регистрировать радиостанцию?": "/blog/tematicheskie-stati/bezlitsenzionnye-chastoty-v-rf-nuzhno-li-registrirovat-radiostantsiyu/",
"Как убедить руководителя перейти на VoIP?": "/blog/tematicheskie-stati/kak-ubedit-rukovoditelya-pereyti-na-voip/",
"Как IP телефония расширяет границы офиса": "/blog/tematicheskie-stati/kak-ip-telefoniya-rasshiryaet-granitsy-ofisa/",
"VoiP Yeastar для улучшения качества обслуживания клиентов": "/blog/tematicheskie-stati/voip-yeastar-dlya-uluchsheniya-kachestva-obsluzhivaniya-klientov/",
"SIP-телефония SIP-протокол ключевые возможности": "/blog/tematicheskie-stati/sip-telefoniya-sip-protokol-klyuchevye-vozmozhnosti/",
"Преимущества традиционных раций для транспортных компаний ASEAN и не только": "/blog/tematicheskie-stati/preimushchestva-traditsionnykh-ratsiy-dlya-transportnykh-kompaniy-asean-i-ne-tolko/",
"Современные возможности коммуникаций и виды связи": "/blog/tematicheskie-stati/sovremennye-vozmozhnosti-kommunikatsiy-i-vidy-svyazi/",
"Mototrbo Capacity Max - система полного транкинга от Motorola": "/blog/tematicheskie-stati/mototrbo-capacity-max-sistema-polnogo-trankinga-ot-motorola/",
"Специализированные устройства и ПО Motorola Solutions для служб реагирования": "/blog/tematicheskie-stati/spetsializirovannye-ustroystva-i-po-motorola-solutions-dlya-sluzhb-reagirovaniya/",
"Будущее стандарта DMR и аналого-цифровой миграции": "/blog/tematicheskie-stati/budushchee-standarta-dmr-i-analogo-tsifrovoy-migratsii/",
"Дешевая связь при помощи DECT раций и мобильных телефонов": "/blog/tematicheskie-stati/deshevaya-svyaz-pri-pomoshchi-dect-ratsiy-i-mobilnykh-telefonov/",
"Как сэкономить на офисной связи используя VoIP-шлюз": "/blog/tematicheskie-stati/kak-sekonomit-na-ofisnoy-svyazi-ispolzuya-voip-shlyuz/",
"Что такое трансивер?": "/blog/tematicheskie-stati/chto-takoe-transiver/",
"Что такое радиостанция (рация)?": "/blog/tematicheskie-stati/chto-takoe-radiostantsiya-ratsiya-/",
"Решения на базе оборудования Motorola для розничных сетей": "/blog/tematicheskie-stati/resheniya-na-baze-oborudovaniya-motorola-dlya-roznichnykh-setey/",
"Применение IP-АТС для организации эффективной связи внутри компании": "/blog/tematicheskie-stati/primenenie-ip-ats-dlya-organizatsii-effektivnoy-svyazi-vnutri-kompanii/",
"Взрывозащищенное оборудование связи": "/blog/tematicheskie-stati/vzryvozashchishchennoe-oborudovanie-svyazi/",
"NXDN – новый протокол цифровой радиосвязи": "/blog/tematicheskie-stati/nxdn-novyy-protokol-tsifrovoy-radiosvyazi/",
"Цифровая радиосвязь с берега на катер": "/blog/tematicheskie-stati/tsifrovaya-radiosvyaz-s-berega-na-kater/",
"7 фактов о Yealink которые необходимо знать если вас интересует VoIP-телефония": "/blog/tematicheskie-stati/7-faktov-o-yealink-kotorye-neobkhodimo-znat-esli-vas-interesuet-voip-telefoniya/",
"Решение по организации IP-телефонии для офиса на базе оборудования Yeastar и Yealink": "/blog/tematicheskie-stati/reshenie-po-organizatsii-ip-telefonii-dlya-ofisa-na-baze-oborudovaniya-yeastar-i-yealink/",
"Диапазоны и типы портативных радиостанций": "/blog/tematicheskie-stati/diapazony-i-tipy-portativnykh-radiostantsiy/",
"Как повысить прибыльность с IP-АТС?": "/blog/tematicheskie-stati/kak-povysit-pribylnost-s-ip-ats/",
"Развитие радиосвязи: виды радиостанций": "/blog/tematicheskie-stati/razvitie-radiosvyazi-vidy-radiostantsiy/",
"Стандарт TETRA": "/blog/tematicheskie-stati/standart-tetra/",
"Расшифровка аббревиатур ATEX на радиостанциях": "/blog/tematicheskie-stati/rasshifrovka-abbreviatur-atex-na-radiostantsiyakh/",
"Архитектура SIP телефонии": "/blog/tematicheskie-stati/arkhitektura-sip-telefonii/",
"IP-телефония - что это и как работает": "/blog/tematicheskie-stati/ip-telefoniya-chto-eto-i-kak-rabotaet/",
"Как самостоятельно подключить IP-телефонию": "/blog/tematicheskie-stati/kak-samostoyatelno-podklyuchit-ip-telefoniyu/",
"Настройка OpenVPN-туннеля для IP-телефонов Yealink": "/blog/tematicheskie-stati/nastroyka-openvpn-tunnelya-dlya-ip-telefonov-yealink-/",
"Как настроить IP-АТС?": "/blog/tematicheskie-stati/kak-nastroit-ip-ats/",
"IP-камеры как средство организации видеонаблюдения": "/blog/tematicheskie-stati/ip-kamery-kak-sredstvo-organizatsii-videonablyudeniya/",
"Что такое IP-телефония?": "/blog/tematicheskie-stati/chto-takoe-ip-telefoniya/",
"Скачать и установить рингтон для IP-телефонов Yealink": "/blog/tematicheskie-stati/skachat-i-ustanovit-rington-dlya-ip-telefonov-yealink/",
"Профессиональные системы радиосвязи для служб охраны и мобильных групп": "/blog/tematicheskie-stati/professionalnye-sistemy-radiosvyazi-dlya-sluzhb-okhrany-i-mobilnykh-grupp-/",
"Как выбрать IP-телефон": "/blog/tematicheskie-stati/kak-vybrat-ip-telefon/",
"5 новых возможностей офисных IP-телефонов": "/blog/tematicheskie-stati/5-novykh-vozmozhnostey-ofisnykh-ip-telefonov/",
"Подготовка к настройке АТС": "/blog/tematicheskie-stati/podgotovka-k-nastroyke-ats/",
"50 лет производителю ICOM": "/blog/tematicheskie-stati/50-let-proizvoditelyu-icom/",
"Второе поколение NEXEDGE": "/blog/tematicheskie-stati/vtoroe-pokolenie-nexedge/",
"Как выбрать рацию для работы и отдыха": "/blog/tematicheskie-stati/kak-vybrat-ratsiyu-dlya-raboty-i-otdykha/",
"Тест Категория 3": "/blog/novosti-marineq/5_ozhidaemykh_tekhnonovinok_kotorye_izmenyat_mir/",
"Автомобильная радиостанция Optim-778": "/blog/novosti-marineq/avtomobilnaya-radiostantsiya-optim-778/",
"Бесплатная связь за границей и на отдыхе": "/blog/novosti-marineq/besplatnaya-svyaz-za-granitsey-i-na-otdykhe/",
"Рации Motorola соответствуют требованиям ПП №969": "/blog/novosti-marineq/ratsii-motorola-sootvetstvuyut-trebovaniyam-pp-969/",
"Лучшее время купить рацию АРГУТ": "/blog/novosti-marineq/luchshee-vremya-kupit-ratsiyu-argut/",
"Почему выгодно купить радиостанцию Терек?": "/blog/novosti-marineq/pochemu-vygodno-kupit-radiostantsiyu-terek/",
"Hytera: радиосвязь на рынке туристических услуг": "/blog/obzory-tovarov/hytera-radiosvyaz-na-rynke-turisticheskikh-uslug/",
"Тестовая статья с превью на Главной": "/blog/obzory-tovarov/chislo-zagruzok-mountain-lion/",
"Тест о дисплеях": "/blog/obzory-tovarov/test-o-displeyakh/",
"Обзор 10 лучших велосипедных брендов": "/blog/obzory-tovarov/obzor_10_luchshikh_velosipednykh_brendov/",
"Hytera предлагает рации и модули для работы на стройке": "/blog/obzory-tovarov/hytera-predlagaet-ratsii-i-moduli-dlya-raboty-na-stroyke/",
"Motorola представляет рации для профессионалов и любителей": "/blog/obzory-tovarov/motorola-predstavlyaet-ratsii-dlya-professionalov-i-lyubiteley/",
"Аргут: портативные рации для работы и отдыха": "/blog/obzory-tovarov/argut-portativnye-ratsii-dlya-raboty-i-otdykha/",
"Icom: обзор новых портативных радиостанций": "/blog/obzory-tovarov/icom-obzor-novykh-portativnykh-radiostantsiy/",
"Линейка Motorola MOTOTRBO": "/blog/obzory-tovarov/lineyka-motorola-mototrbo/",
"Обзор IP-АТС Yeastar S-серии": "/blog/obzory-tovarov/obzor-ip-ats-yeastar-s-serii/",
"Обзор автомобильных радиостанций ICOM": "/blog/obzory-tovarov/obzor-avtomobilnykh-radiostantsiy-icom/",
"Hytera — качественная радиосвязь для профессионалов": "/blog/obzory-tovarov/hytera-kachestvennaya-radiosvyaz-dlya-professionalov/",
"Snom D385 - немецкий IP телефон для крутого офиса": "/blog/obzory-tovarov/snom-d385-nemetskiy-ip-telefon-dlya-krutogo-ofisa/",
"Snom DECT облегчает работу в любых организациях": "/blog/obzory-tovarov/snom-dect-oblegchaet-rabotu-v-lyubykh-organizatsiyakh/",
"Кenwood: обзор портативных и автомобильных раций": "/blog/obzory-tovarov/kenwood-obzor-portativnykh-i-avtomobilnykh-ratsiy/",
"Grandstream: IP-телефония для бизнеса": "/blog/obzory-tovarov/grandstream-ip-telefoniya-dlya-biznesa/",
"Строительные рации для связи в условиях стройки": "/blog/obzory-tovarov/stroitelnye-ratsii-dlya-svyazi-v-usloviyakh-stroyki/",
"Обзор бренда и новинок Snom": "/blog/obzory-tovarov/obzor-brenda-i-novinok-snom/",
"Обзор новой портативной радиостанции Motorola MTP6650": "/blog/obzory-tovarov/obzor-novoy-portativnoy-radiostantsii-motorola-mtp6650/",
"Обзор новых радиостанций Icom": "/blog/obzory-tovarov/obzor-novykh-radiostantsiy-icom/",
"Краткий обзор преимуществ сетевого оборудования MikroTik": "/blog/obzory-tovarov/kratkiy-obzor-preimushchestv-setevogo-oborudovaniya-mikrotik-/",
"Обзор новой портативной радиостанции Motorola ST7500": "/blog/obzory-tovarov/obzor-novoy-portativnoy-radiostantsii-motorola-st7500-/",
"Обзор портативных радиостанций Vector (Вектор)": "/blog/obzory-tovarov/obzor-portativnykh-radiostantsiy-vector-vektor/",
"Мобильный коммуникатор Wave от Motorola Solutions": "/blog/obzory-tovarov/mobilnyy-kommunikator-wave-ot-motorola-solutions/",
"Panasonic KX-NSX: надежная и гибкая UC-платформа": "/blog/obzory-tovarov/panasonic-kx-nsx-nadezhnaya-i-gibkaya-uc-platforma/",
"Обзор IP-АТС Panasonic KX-NCP1000RU  и KX-NCP500RU": "/blog/obzory-tovarov/obzor-ip-ats-panasonic-kx-ncp1000ru-i-kx-ncp500ru-/",
"Обзор SIP DECT телефона Panasonic KX-TGP600": "/blog/obzory-tovarov/obzor-sip-dect-telefona-panasonic-kx-tgp600-/",
"Выбираем подходящий ip-телефон среди представителей Panasonic и Yealink": "/blog/obzory-tovarov/vybiraem-podkhodyashchiy-ip-telefon-sredi-predstaviteley-panasonic-i-yealink/",
"Кто на новенького: обзор IP-телефонов и IP-АТС": "/blog/obzory-tovarov/kto-na-novenkogo-obzor-ip-telefonov-i-ip-ats/",
"Незаметная связь: портативные радиостанции и скрытые гарнитуры": "/blog/obzory-tovarov/nezametnaya-svyaz-portativnye-radiostantsii-i-skrytye-garnitury/",
"Молодым дорогу: обзор новых портативных раций на сайте": "/blog/obzory-tovarov/molodym-dorogu-obzor-novykh-portativnykh-ratsiy-na-sayte/",
"Обзор радиостанций MotoTRBO": "/blog/obzory-tovarov/obzor-radiostantsiy-mototrbo/",
"Промышленные телефоны ТАШ - надежная связь в любых условиях": "/blog/obzory-tovarov/promyshlennye-telefony-tash-nadezhnaya-svyaz-v-lyubykh-usloviyakh/",
"Обзор автомобильных радиостанций Vertex Standard": "/blog/obzory-tovarov/obzor-avtomobilnykh-radiostantsiy-vertex-standard/",
"Рации TurboSky - новинка отечественного рынка": "/blog/obzory-tovarov/ratsii-turbosky-novinka-otechestvennogo-rynka/",
"Обзор раций Kenwood": "/blog/obzory-tovarov/obzor-ratsiy-kenwood/",
"5 достоинств профессиональных портативных радиостанций КОМБАТ": "/blog/obzory-tovarov/5-dostoinstv-professionalnykh-portativnykh-radiostantsiy-kombat/",
"Обзор взрывозащищенных радиостанций Hytera PD795Ex Motorola DP4401 Ex и Kenwood NX-230EXE": "/blog/obzory-tovarov/obzor-vzryvozashchishchennykh-radiostantsiy-hytera-pd795ex-motorola-dp4401-ex-i-kenwood-nx-230exe/",
"Обзор VoIP телефонов Snom серии 7x": "/blog/obzory-tovarov/obzor-voip-telefonov-snom-serii-7x/",
"Первый взгляд на DECT телефон Gigaset A54OH": "/blog/obzory-tovarov/pervyy-vzglyad-na-dect-telefon-gigaset-a54oh/",
"Обзор портативных раций Icom": "/blog/obzory-tovarov/obzor-portativnykh-ratsiy-icom-/",
"Обзор радиостанции Vertex VZ-30": "/blog/obzory-tovarov/obzor-radiostantsii-vertex-vz-30/",
"Обзор новых портативных раций КОМБАТ T-34": "/blog/obzory-tovarov/obzor-novykh-portativnykh-ratsiy-kombat-t-34/",
"AVAYA – коммуникационные решения нового уровня": "/blog/obzory-tovarov/avaya-kommunikatsionnye-resheniya-novogo-urovnya/",
"Обзор телефонов Panasonic": "/blog/obzory-tovarov/obzor-telefonov-panasonic-/",
"Автомобильные Си-Би радиостанции": "/blog/obzory-tovarov/avtomobilnye-si-bi-radiostantsii/",
"Обзор портативных раций Vertex Standard": "/blog/obzory-tovarov/obzor-portativnykh-ratsiy-vertex-standard/",
"Megajet 350 vs Yosan Excalibur – обзор Си-Би радиостанций": "/blog/obzory-tovarov/megajet-350-vs-yosan-excalibur-obzor-si-bi-radiostantsiy/",
"Обзор IP-телефона DECT Yealink SIP-W52P": "/blog/obzory-tovarov/obzor-ip-telefona-dect-yealink-sip-w52p/",
"IP-телефония на примере SIP-телефона от Yealink": "/blog/obzory-tovarov/ip-telefoniya-na-primere-sip-telefona-ot-yealink/",
"IP-телефоны – выбор связи для Вашего бизнеса": "/blog/obzory-tovarov/ip-telefony-vybor-svyazi-dlya-vashego-biznesa/",
"Обзор факсов Panasonic и факс-серверов Yeastar: виды особенности как выбрать и купить факс": "/blog/obzory-tovarov/obzor-faksov-panasonic-i-faks-serverov-yeastar-vidy-osobennosti-kak-vybrat-i-kupit-faks/",
"Разбираем стандарт DMR на примере радиостанций Hytera": "/blog/obzory-tovarov/razbiraem-standart-dmr-na-primere-radiostantsiy-hytera/",
"Радиостанции Icom как образец качества японского производства": "/blog/obzory-tovarov/radiostantsii-icom-kak-obrazets-kachestva-yaponskogo-proizvodstva/",
"Обзор любительских КВ трансиверов": "/blog/obzory-tovarov/obzor-lyubitelskikh-kv-transiverov/",
"Обзор раций Hytera": "/blog/obzory-tovarov/obzor-ratsiy-hytera/",
"IP-телефоны Panasonic и Escene: сравнение": "/blog/obzory-tovarov/ip-telefony-panasonic-i-escene-sravnenie/",
"VoIP-шлюзы Yeastar NeoGate: TA400 TA410 и TA810": "/blog/obzory-tovarov/voip-shlyuzy-yeastar-neogate-ta400-ta410-i-ta810/",
"SIP телефоны Yealink: обзор линеек T3 и T4": "/blog/obzory-tovarov/sip-telefony-yealink-obzor-lineek-t3-i-t4/",
"Обзор портативных радиостанций Kenwood": "/blog/obzory-tovarov/obzor-portativnykh-radiostantsiy-kenwood/",
"IP телефоны Grandstream для малого бизнеса: обзор": "/blog/obzory-tovarov/ip-telefony-grandstream-dlya-malogo-biznesa-obzor/",
"Цифровые радиостанции eVerge™ от Vertex Standard": "/blog/obzory-tovarov/tsifrovye-radiostantsii-everge-ot-vertex-standard/",
"Рынок SIP-телефонов в России": "/blog/obzory-tovarov/rynok-sip-telefonov-v-rossii/",
"Как выбрать портативные рации для охоты и рыбалки": "/blog/obzory-tovarov/kak-vybrat-portativnye-ratsii-dlya-okhoty-i-rybalki/",
"SIP-телефоны Yealink T4: обзор серии": "/blog/obzory-tovarov/sip-telefony-yealink-t4-obzor-serii/",
"SIP-телефоны Escene": "/blog/obzory-tovarov/sip-telefony-escene/",
"Обзор SIP-телефона Fanvil X5": "/blog/obzory-tovarov/obzor-sip-telefona-fanvil-x5/",
"Обзор IP-АТС Atcom": "/blog/obzory-tovarov/obzor-ip-ats-atcom/",
"Обзор IP-АТС от Yeastar": "/blog/obzory-tovarov/obzor-ip-ats-ot-yeastar/",
"Обзор IP-телефона Escene ES292": "/blog/obzory-tovarov/obzor-ip-telefona-escene-es292/",
"Таблица совместимости для гарнитур Mairdi": "/blog/obzory-tovarov/tablitsa-sovmestimosti-dlya-garnitur-mairdi/",
"Рации VERTEX: сравнение характеристик": "/blog/obzory-tovarov/ratsii-vertex-sravnenie-kharakteristik/",
"Обзор автомобильной радиостанции MegaJet MJ-600 PLUS": "/blog/obzory-tovarov/obzor-avtomobilnoy-radiostantsii-megajet-mj-600-plus/",
"Обзор автомобильных Си-Би раций Megajet": "/blog/obzory-tovarov/obzor-avtomobilnykh-si-bi-ratsiy-megajet/",
"Обзор портативных радиостанций для охоты рыбалки и другого активного отдыха": "/blog/obzory-tovarov/obzor-portativnykh-radiostantsiy-dlya-okhoty-rybalki-i-drugogo-aktivnogo-otdykha/",
"Радиостанции Megajet: особенности и разнообразие": "/blog/obzory-tovarov/radiostantsii-megajet-osobennosti-i-raznoobrazie/",
"Как выбрать автомобильную рацию": "/blog/obzory-tovarov/kak-vybrat-avtomobilnuyu-ratsiyu/",
"Grandstream расширяет линейку IP-видеотелефонов": "/blog/obzory-tovarov/grandstream-rasshiryaet-lineyku-ip-videotelefonov/",
"Обеспечение телефонной связью удаленных подвижных объектов": "/blog/obzory-tovarov/obespechenie-telefonnoy-svyazyu-udalennykh-podvizhnykh-obektov-/",
}

for name in old_url:
    if name in new_url and old_url[name] != new_url[name]:
        dict_url[name] = [old_url[name], new_url[name]]

# for name in dict_url:
#     print(f'"https://landcomm.ru{dict_url[name][0]}",')

print()
print('***********************************************************************************************')
print()

# for name in dict_url:
#     print(f'"http://test.landcomm.ru{dict_url[name][1]}",')

print()
print('***********************************************************************************************')
print()

for name in dict_url:
    #print(f"RewriteRule {dict_url[name][0]}$ https://landcomm.ru{dict_url[name][1]} [R=301,L]")
    print(f"RewriteRule ^(.*){dict_url[name][0][1:]}$ https://landcomm.ru{dict_url[name][1]} [R=301,L]")

print(f"old - {len(old_url)}")
print(f"new - {len(new_url)}")
print(f"all - {len(dict_url)}")


print('Ok')
toc = time()
print(str(round((toc - tic), 1)) + ' sec')